### ISSUE TITLE
SDL not found

### ISSUE THREAD

**Issue by 2tbc1887** [hcgcloud/pterodactyl-unturned#10]
When I run the server, immediately after the server gets marked as online, this error appears in the console: 
`Warning: failed to init SDL thread priority manager: SDL not found`
I am unable to connect in game, and the system has been rebooted since the egg was installed

**Comment by tyson239** [comment]
Hi, this problem seems to be caused by steamcmd, but it should not affect the running of the server. You can try to check whether the server has been successfully installed, or provide a complete log so that we can locate the problem.
