### ISSUE TITLE
Random Crash with this Error

### ISSUE THREAD

**Issue by griffindor301** [hcgcloud/pterodactyl-unturned#2]
Hello im using Hcgcloud's unturned egg and i keep running into this issue on one server any idea why?

**Comment by griffindor301** [comment]
/entrypoint.sh: line 23: 49 Aborted (core dumped) ${MODIFIED_STARTUP}
If there was an error above when trying to stop your server, it can usually be ignored.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 0
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server process detected as entering a crashed state; rebooting.

**Comment by tyson239** [comment]
Hello, can you provide directory structure of that server?

**Comment by griffindor301** [comment]
The Structure to the Main server files is
/home/container/Servers/unturned/

**Comment by tyson239** [comment]
Just the root folder `/home/container`, to check if the Unturned and RocketMod have been installed properly.

**Comment by tyson239** [comment]
Also is there any errors from the daemon?
or try
```
cd /srv/daemon/ && npm run diagnostics
```

**Comment by griffindor301** [comment]
There are no errors through the daemon and its only the one server acting up the others are fine

**Comment by griffindor301** [comment]
![Files](https://user-images.githubusercontent.com/39884393/74622019-4870d400-510d-11ea-9545-53f38c4a72ce.PNG)
There is the whole directory

**Comment by tyson239** [comment]
Any other servers using this egg? Can they work properly?

**Comment by griffindor301** [comment]
I have 4 servers running on that egg with no issues so not sure on why its just the one.

**Comment by tyson239** [comment]
i am not sure whats going wrong if there's no error logs, maybe you can try rebuild the container or delete all files(if it's fresh installed) and reinstall.
If you still get this, please provide the full log from the console and I will do further checks.

**Comment by griffindor301** [comment]
Here is two of my Rocket Logs.I don't see anything that should random cause a crash with that error.
[Rocket.1581994154.log](https://github.com/hcgcloud/pterodactyl-unturned/files/4217127/Rocket.1581994154.log)
[Rocket.1581990944.log](https://github.com/hcgcloud/pterodactyl-unturned/files/4217128/Rocket.1581990944.log)

**Comment by tyson239** [comment]
Is you server crashed after the these logs were recorded?

**Comment by tyson239** [comment]
I think this problem is caused by the plugins you installed.

```
[02/18/2020 01:26:26] [Error] Unable to find spawn table for resolve with id 33333
[02/18/2020 01:26:26] [Error] Failed to respawn an item with ID 0 from type Mechanic_1 [0]
```

```
[02/18/2020 01:29:16] [Error] Could not find dependency: PlayerStats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[02/18/2020 01:29:19] [Error] Could not find dependency: PlayerStats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

Try to remove the related plugins and try again.

**Comment by griffindor301** [comment]
Yeah Fixed the dependency one already and The Unable to find spawn table is from npc's says it shouldn't cause any issues is that not true?

**Comment by tyson239** [comment]
Maybe, you can check if there are any problems after solving the dependency issues.

**Comment by griffindor301** [comment]
Here is something new to that error

Stacktrace:
Native stacktrace:
mono(+0xc8514) [0x556c9bcde514]
mono(+0x1217ce) [0x556c9bd377ce]
mono(+0x3d7e3) [0x556c9bc537e3]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x7f3a61af3890]
mono(+0x231cc7) [0x556c9be47cc7]
mono(+0x233fcc) [0x556c9be49fcc]
mono(+0x2366ca) [0x556c9be4c6ca]
mono(+0x2292c4) [0x556c9be3f2c4]
mono(+0x214de1) [0x556c9be2ade1]
mono(+0x1f077b) [0x556c9be0677b]
mono(+0x1f08fa) [0x556c9be068fa]
mono(+0x1f15e0) [0x556c9be075e0]
mono(mono_string_new+0x1e) [0x556c9be0763e]
mono(+0x1c837f) [0x556c9bdde37f]
mono(+0x1c2be1) [0x556c9bdd8be1]
mono(+0x28214a) [0x556c9be9814a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f3a61ae86db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f3a615f988f]
Debug info from gdb:

================================================================
=

Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.

=================================================================

/entrypoint.sh: line 23: 48 Aborted (core dumped) ${MODIFIED_STARTUP}
If there was an error above when trying to stop your server, it can usually be ignored.

**Comment by tyson239** [comment]
Is threre's anything before the error?

**Comment by griffindor301** [comment]
Just regular stuff like players talking etc

**Comment by tyson239** [comment]
I think it would be more likely to plugin issues. Could you do some exclusion checks for plugins?
